### ISSUE TITLE
GitHub Actionsで自動デプロイ

### ISSUE THREAD

**Issue by MasashiFukuzawa** [MasashiFukuzawa/development-efficiency-measurement#13]
# Issue
> sudo: clasp: command not found

- `clasp push`が上手く行かずに一旦断念した
  - https://github.com/MasashiFukuzawa/development-efficiency-measurement/pull/14/checks?check_run_id=1018007954
- 参考:
  - https://undersooon.hatenablog.com/entry/2019/12/25/200636
  - https://github.com/momumomu/clasp_ci_sample

# 流れメモ
1. `.github/workflows/config.yml`を編集

```yml
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ID_TOKEN: ${{ secrets.ID_TOKEN }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  SCRIPT_ID: ${{ secrets.SCRIPT_ID }}

on: push

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn install
        run: yarn install

      - name: Eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,js}'

      - name: Eslint
        run: yarn lint

      - name: Jest
        run: yarn test

      - name: Set access_token into clasprc.json
        run: sudo sed -i -e "s/\"access_token\":\"DUMMY\"/\"access_token\":\"${ACCESS_TOKEN}\"/" clasprc.json
      - name: Set id_token into clasprc.json
        run: sudo sed -i -e "s/\"id_token\":\"DUMMY\"/\"id_token\":\"${ID_TOKEN}\"/" clasprc.json
      - name: Set clientId into clasprc.json
        run: sudo sed -i -e "s/\"clientId\":\"DUMMY\"/\"clientId\":\"${CLIENT_ID}\"/" clasprc.json
      - name: Set clientSecret into clasprc.json
        run: sudo sed -i -e "s/\"clientSecret\":\"DUMMY\"/\"clientSecret\":\"${CLIENT_SECRET}\"/" clasprc.json
      - name: Set refresh_token into clasprc.json
        run: sudo sed -i -e "s@\"refresh_token\":\"DUMMY\"@\"refresh_token\":\"${REFRESH_TOKEN}\"@" clasprc.json
      - name: Set scriptId into .clasp.json
        run: |
          sudo sed -i -e "s/\"scriptId\":\"DUMMY\"/\"scriptId\":\"${SCRIPT_ID}\"/" .clasp.json
      - name: Set clasprc
        run: sudo cat clasprc.json > ~/.clasprc.json

      - name: Set clasp path
        run: echo "::add-path::$(pwd)/node_modules/.bin"

      - name: Clasp push
        run: yarn push

      - name: Claps deploy
        run: yarn deploy
```

2. secretsに秘匿情報を登録
- `~/.clasprc.json`から情報を取得
- script_idは`.clasp.json`から取得
![image](https://user-images.githubusercontent.com/44726460/90975674-64987680-e571-11ea-9c95-dcee6e40fd36.png)

3. `.clasp.json`からscript_idの値を削除

4. `.gitignore`から`.clasp.json`を削除

5. `package.json`を修正

6. push
